CREATE TABLE departments (
	dept_no VARCHAR (5) NOT NULL PRIMARY KEY,
	dept_name VARCHAR (50) NOT NULL
)

CREATE TABLE dept_emp(
	emp_no INTEGER NOT NULL,
	dept_no VARCHAR (5) NOT NULL
)

CREATE TABLE dept_manager (
	emp_no INTEGER NOT NULL PRIMARY KEY,
	dept_no VARCHAR (5) NOT NULL
)

CREATE TABLE employees (
	emp_no INTEGER NOT NULL PRIMARY KEY,
	emp_title_id VARCHAR (5) NOT NULL,
	birth_date DATE NOT NULL,
	first_name VARCHAR (50) NOT NULL,
	last_name VARCHAR (50) NOT NULL,
	sex VARCHAR (1) NOT NULL,
	hire_date DATE NOT NULL
)

CREATE TABLE salaries (
	emp_no INTEGER NOT NULL PRIMARY KEY,
	salary INTEGER NOT NULL
)

CREATE TABLE titles (
	title_id VARCHAR (5) NOT NULL PRIMARY KEY,
	title VARCHAR (30) NOT NULL
)